"""add/update tables

Revision ID: 086d540240ee
Revises: c2427de70707
Create Date: 2026-02-01 20:43:49.031271

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '086d540240ee'
down_revision = 'c2427de70707'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
