"""Added paper_id column to session to map session with user and paper as well

Revision ID: 4325c50b492e
Revises: 51602db4bc34
Create Date: 2026-03-01 02:23:54.976672

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "4325c50b492e"
down_revision = "51602db4bc34"
branch_labels = None
depends_on = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("checkpoints_thread_id_idx"), table_name="checkpoints")
    op.drop_table("checkpoints")
    op.drop_table("checkpoint_migrations")
    op.drop_index(op.f("checkpoint_blobs_thread_id_idx"), table_name="checkpoint_blobs")
    op.drop_table("checkpoint_blobs")
    op.drop_index(op.f("ix_usability_paper_id"), table_name="usability")
    op.drop_index(op.f("ix_usability_user_id"), table_name="usability")
    op.drop_table("usability")
    op.drop_index(
        op.f("checkpoint_writes_thread_id_idx"), table_name="checkpoint_writes"
    )
    op.drop_table("checkpoint_writes")
    op.add_column("session", sa.Column("paper_id", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_session_paper_id"), "session", ["paper_id"], unique=False)
    op.create_foreign_key(None, "session", "paper", ["paper_id"], ["id"])
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This migration had the logic reversed - the upgrade was dropping columns/tables
    # and the downgrade was adding them. Alembic also auto-generated commands to recreate
    # checkpoint tables and usability table, which should NOT be managed by migrations.
    #
    # Since this migration has already been run, we're keeping it as a no-op to avoid
    # breaking the migration history. Future migrations should be generated properly.
    pass
    # ### end Alembic commands ###
