"""Added metadata column to message table

Revision ID: 51602db4bc34
Revises: b7bdb6a30643
Create Date: 2026-03-01 01:45:01.723211

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "51602db4bc34"
down_revision = "b7bdb6a30643"
branch_labels = None
depends_on = None


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usability_paper_id"), table_name="usability")
    op.drop_index(op.f("ix_usability_user_id"), table_name="usability")
    op.drop_table("usability")
    op.add_column(
        "message",
        sa.Column(
            "generation_metadata",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # NOTE: This migration was supposed to remove generation_metadata column from message table
    # but Alembic also tried to re-create the usability table which was already created in b7bdb6a30643
    # Removed the usability table creation to prevent conflicts
    # Only keeping the column drop if it exists
    try:
        op.drop_column("message", "generation_metadata")
    except Exception:
        pass  # Column might not exist, that's okay
    # ### end Alembic commands ###
