"""added usability table

Revision ID: 72fba8597d34
Revises: a9b6b6c3331a
Create Date: 2026-02-18 17:45:16.851442

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '72fba8597d34'
down_revision = 'a9b6b6c3331a'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
