"""missing columns

Revision ID: 7d958c5c63fd
Revises: 577936a0f778
Create Date: 2026-06-23 09:35:16.993575

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '7d958c5c63fd'
down_revision = '577936a0f778'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('paper_arxiv_id_key'), 'paper', type_='unique')
    op.create_unique_constraint('uq_paper_user_arxiv', 'paper', ['user_id', 'arxiv_id'])
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=True)
    op.create_unique_constraint('uq_usability_user_paper', 'usability', ['user_id', 'paper_id'])
    op.add_column('user_settings', sa.Column('summary_model', sa.String(length=100), nullable=True))
    op.add_column('user_settings', sa.Column('usability_model', sa.String(length=100), nullable=True))
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_settings_user_id'), table_name='user_settings')
    op.create_index(op.f('ix_user_settings_user_id'), 'user_settings', ['user_id'], unique=False)
    op.drop_column('user_settings', 'usability_model')
    op.drop_column('user_settings', 'summary_model')
    op.drop_constraint('uq_usability_user_paper', 'usability', type_='unique')
    op.drop_index(op.f('ix_profile_user_id'), table_name='profile')
    op.create_index(op.f('ix_profile_user_id'), 'profile', ['user_id'], unique=False)
    op.drop_constraint('uq_paper_user_arxiv', 'paper', type_='unique')
    op.create_unique_constraint(op.f('paper_arxiv_id_key'), 'paper', ['arxiv_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
