"""Added service catalog table

Revision ID: 9d32e340bd25
Revises: 09216880bdf3
Create Date: 2026-03-03 16:09:53.463498

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d32e340bd25'
down_revision = '09216880bdf3'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('service_type', sa.Enum('WEB_SEARCH', 'WEB_SCRAPE', 'LLM', 'EMBEDDING', 'RERANK', 'VECTOR_STORE', name='servicetype', native_enum=False, length=50), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_service_catalog_service_type'), 'service_catalog', ['service_type'], unique=False)
    op.create_index(op.f('ix_service_catalog_slug'), 'service_catalog', ['slug'], unique=True)
    
    op.add_column('user_settings', sa.Column('custom_summary_instructions', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('usability_analysis_instructions', sa.String(), nullable=True))
    op.add_column('user_settings', sa.Column('api_keys_encrypted', sa.Text(), nullable=True))
    op.drop_column('user_settings', 'custom_instructions')
    op.drop_column('user_settings', 'dark_mode_enabled')
    op.drop_column('user_settings', 'language_preference')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('language_preference', sa.VARCHAR(length=8), server_default=sa.text("'en'::character varying"), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('dark_mode_enabled', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('user_settings', sa.Column('custom_instructions', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('user_settings', 'api_keys_encrypted')
    op.drop_column('user_settings', 'usability_analysis_instructions')
    op.drop_column('user_settings', 'custom_summary_instructions')
    op.create_table('usability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paper_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain_applicability', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('reproducibility_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('new_tech_applicability', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('impact_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], name=op.f('usability_paper_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('usability_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usability_pkey'))
    )
    op.create_index(op.f('ix_usability_user_id'), 'usability', ['user_id'], unique=False)
    op.create_index(op.f('ix_usability_paper_id'), 'usability', ['paper_id'], unique=False)
    op.drop_index(op.f('ix_service_catalog_slug'), table_name='service_catalog')
    op.drop_index(op.f('ix_service_catalog_service_type'), table_name='service_catalog')
    op.drop_table('service_catalog')
    # ### end Alembic commands ###
