"""add paper_summary column

Revision ID: a9b6b6c3331a
Revises: e9973afeae95
Create Date: 2026-02-17 16:34:58.156181

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'a9b6b6c3331a'
down_revision = 'e9973afeae95'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('paper_summary', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'paper_summary')
    # ### end Alembic commands ###
