"""add/update tables

Revision ID: c2427de70707
Revises: 
Create Date: 2026-02-01 11:04:30.566325

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c2427de70707'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('topic_preferences', sa.String(length=1024), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profile', 'topic_preferences')
    # ### end Alembic commands ###
