"""Phase 2 recsys

Revision ID: c268fa0c7413
Revises: 14df2401d013
Create Date: 2026-05-13 22:16:16.626679

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c268fa0c7413'
down_revision = '14df2401d013'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('arxiv_catalog',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('arxiv_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('authors', sa.String(length=2048), nullable=True),
    sa.Column('categories', sa.String(length=256), nullable=True),
    sa.Column('primary_category', sa.String(length=50), nullable=True),
    sa.Column('published_date', sa.String(length=50), nullable=True),
    sa.Column('updated_date', sa.String(length=50), nullable=True),
    sa.Column('pdf_url', sa.String(), nullable=True),
    sa.Column('paper_url', sa.String(), nullable=True),
    sa.Column('indexed_in_qdrant', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_arxiv_catalog_arxiv_id'), 'arxiv_catalog', ['arxiv_id'], unique=True)
    op.create_index(op.f('ix_arxiv_catalog_primary_category'), 'arxiv_catalog', ['primary_category'], unique=False)
    op.create_index(op.f('ix_arxiv_catalog_published_date'), 'arxiv_catalog', ['published_date'], unique=False)
    op.add_column('paper', sa.Column('keywords', sa.String(length=1024), nullable=True))
    op.drop_column('user_settings', 'usability_model')
    op.drop_column('user_settings', 'summary_model')
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_settings', sa.Column('summary_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('user_settings', sa.Column('usability_model', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.drop_column('paper', 'keywords')
    op.create_table('usability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paper_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain_applicability', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('reproducibility_score', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('new_tech_applicability', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('impact_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], name=op.f('usability_paper_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('usability_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usability_pkey'))
    )
    op.create_index(op.f('ix_usability_user_id'), 'usability', ['user_id'], unique=False)
    op.create_index(op.f('ix_usability_paper_id'), 'usability', ['paper_id'], unique=False)
    op.drop_index(op.f('ix_arxiv_catalog_published_date'), table_name='arxiv_catalog')
    op.drop_index(op.f('ix_arxiv_catalog_primary_category'), table_name='arxiv_catalog')
    op.drop_index(op.f('ix_arxiv_catalog_arxiv_id'), table_name='arxiv_catalog')
    op.drop_table('arxiv_catalog')
    # ### end Alembic commands ###
