"""Added resources table

Revision ID: cc5a06fd06e0
Revises: 3275ccd44710
Create Date: 2026-04-01 19:42:10.505428

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cc5a06fd06e0'
down_revision = '3275ccd44710'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usability',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('paper_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('domain_applicability', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('reproducibility_score', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('new_tech_applicability', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'{}'::json"), autoincrement=False, nullable=False),
    sa.Column('impact_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['paper.id'], name=op.f('usability_paper_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('usability_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('usability_pkey'))
    )
    op.create_index(op.f('ix_usability_user_id'), 'usability', ['user_id'], unique=False)
    op.create_index(op.f('ix_usability_paper_id'), 'usability', ['paper_id'], unique=False)
    # ### end Alembic commands ###
