"""Updated user settings table

Revision ID: d8dd995d8279
Revises: 9d32e340bd25
Create Date: 2026-03-03 22:13:15.422979

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "d8dd995d8279"
down_revision = "9d32e340bd25"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert TEXT column to JSONB with explicit USING clause
    # Set existing encrypted TEXT values to NULL and convert to JSONB type
    op.execute(
        """
        ALTER TABLE user_settings 
        ALTER COLUMN api_keys_encrypted TYPE JSONB 
        USING CASE 
            WHEN api_keys_encrypted IS NULL THEN NULL 
            ELSE '[]'::jsonb 
        END
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Convert JSONB back to TEXT
    op.execute(
        """
        ALTER TABLE user_settings 
        ALTER COLUMN api_keys_encrypted TYPE TEXT 
        USING CASE 
            WHEN api_keys_encrypted IS NULL THEN NULL 
            ELSE api_keys_encrypted::text 
        END
        """
    )
    # ### end Alembic commands ###
