"""added ingested column to paper

Revision ID: e9973afeae95
Revises: 086d540240ee
Create Date: 2026-02-13 01:34:48.726301

"""

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'e9973afeae95'
down_revision = '086d540240ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('paper', sa.Column('ingested', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('paper', 'ingested')
    # ### end Alembic commands ###
